### ISSUE TITLE
Some deployment issues about hexo-gradient.netlify.com/🤔

### ISSUE THREAD

**Issue by Cloud300** [RandomAdversary/Gradient#20]
I like gradient very much, let me introduce my situation:
I am from mainland china
Accessing Github in China is very slow
and so
I want to ask,
Are the pictures in this theme in the github repository?
Or deploy on another server?
If I want to use it, can I just put these files in my theme folder?
![github'](https://user-images.githubusercontent.com/39040440/69942995-f235c100-151f-11ea-932f-5d4d92c3a8c7.png)
![本地](https://user-images.githubusercontent.com/39040440/69943206-24472300-1520-11ea-891b-9baba5649eb0.png)

**Comment by DeepSpaceHarbor** [comment]
I didn't know that netlify is blocked in china. 😔
Attached bellow are screenshots from the theme and I will look into adding additional deploy server, and avoid this issue in the future.

![image](https://user-images.githubusercontent.com/11393457/69946661-6191bd80-14ec-11ea-8e36-80e4b2bc4f21.png)
![image](https://user-images.githubusercontent.com/11393457/69946695-6fdfd980-14ec-11ea-8954-dbafec670006.png)

**Comment by DeepSpaceHarbor** [comment]
If you want to use it, copy the theme into themes folder, and change the [_config.yml](https://github.com/DeepSpaceHarbor/Gradient/blob/demo-content/_config.yml#L76) file.

**Comment by Cloud300** [comment]
alright, thank you very much.
  If possible, I hope to have a Chinese tutorial.  
After all, Chinese is the most used worldwide.  
Of course this is just one of my suggestions.  
But thank you very much😄


来自 魅族 16s

-------- 原始邮件 --------
发件人：Borche <notifications@github.com>
时间：2019年12月2日 17:24
收件人：DeepSpaceHarbor/Gradient <Gradient@noreply.github.com>
抄送："Cloud.Sir" <13969132120@163.com>,Author <author@noreply.github.com>
主题：Re: [DeepSpaceHarbor/Gradient] Some deployment issues about hexo-gradient.netlify.com/🤔 (#20)

**Comment by DeepSpaceHarbor** [comment]
That will be hard to implement because don't speak Chinese, but, this is a public repo and all contributions are welcome.

**Comment by DeepSpaceHarbor** [comment]
The preview is now hosted on github pages.
